// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldrczklaunromrxnkhxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkcmN6a2xhdW5yb21yeG5raHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTkwMjQsImV4cCI6MjA2NTU3NTAyNH0.m84IlcBVYXQKnXLjvl5EKKsuU32VqQl1Mb4uR3kmGAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);